#pragma once
#include "matmul/Matmul.h"
#include "relu/Relu.h"
#include "sum/Sum.h"
#include "log/Log.h"
#include "sigmoid/Sigmoid.h"
#include "softmax/Softmax.h"
#include "add/Add.h"
#include "mul/Mul.h"